name: All Tests and Builds

on:
  push:
  pull_request:

jobs:
  alternative_targets:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [wasm32-unknown-unknown, wasm32-wasi, wasm32-unknown-emscripten, aarch64-apple-ios, aarch64-linux-android]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          export RUST_BACKTRACE=1
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack --version
      - run: cargo build --target ${{ matrix.target }}  --color=always
